<!-- Shared CV body (web + PDF). Vita: _content-vita.qmd. PDF-only early: _content-early.qmd. -->

## Publications

### Refereed Journal Papers

1. K. Abduaziz, **C. Han**, and J. Shin, “Semi-supervised Traceability Analysis of Investigative Scanners of Darknet Traffic,” *Computers & Security*, Dec 2025. [[DOI]](https://doi.org/10.1016/j.cose.2025.104681)
2. K. Miyamoto, M. Iida, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Consolidating Packet-Level Features for Effective Network Intrusion Detection: A Novel Session-Level Approach,” *IEEE ACCESS*, Nov 2023. [[DOI]](https://doi.org/10.1109/ACCESS.2023.3335600) [[PDF]](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10325518)
4. Y. Chang, H. Chen, **C. Han**, T. Morikawa, T. Takahashi, and T. Lin, “FINISH: Efficient and Scalable NMF-based Federated Learning for Detecting Malware Activities,” *IEEE Transactions on Emerging Topics in Computing (TETC)*, Jul 2023. [[DOI]](https://doi.org/10.1109/TETC.2023.3292924) [[PDF]](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10179267)
5. A. Tanaka, **C. Han**, and T. Takahashi, “Detecting Coordinated Internet-Wide Scanning by TCP/IP Header Fingerprint,” *IEEE ACCESS*, Feb 2023. [[DOI]](https://doi.org/10.1109/ACCESS.2023.3249474) [[PDF]](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10054012) [[Slides]](https://drive.google.com/file/d/17RIq3J7ZxuwiQUxk6Hlyl8FGR7_4ZMde/view?usp=sharing) [[Related Slides (Japanese)]](https://drive.google.com/file/d/1sM0jIU7vBlNwvE-8LDP5-9nYEdorddck/view?usp=sharing)
6. T. He, **C. Han**, R. Isawa, T. Takahashi, S. Kijima, and J. Takeuchi, “Scalable and Fast Algorithm for Constructing Phylogenetic Trees with Application to IoT Malware Clustering,” *IEEE ACCESS*, Jan 2023. [[DOI]](https://doi.org/10.1109/ACCESS.2023.3238711) [[PDF]](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10024280) [[Related Slides (Japanese)]](https://drive.google.com/file/d/1pgPkml6uFMmQG3IdFpt0INAr_9kBubm2/view?usp=sharing)
7. R. Ishibashi, K. Miyamoto, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Generating Labeled Training Datasets Towards Unified Network Intrusion Detection Systems,” *IEEE ACCESS*, May 2022. [[DOI]](https://doi.org/10.1109/ACCESS.2022.3176098) [[PDF]](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9777676) [[Related Slides (@AsiaJCIS'21)]](https://drive.google.com/file/d/1WSmsCvpRJ2spJIaBS2sIWdYf6bAt5_wp/view?usp=sharing) [[Codes & Datasets]](https://github.com/suuri-kyudai/Generating-Dataset-for-NIDS)
8. **C. Han**, J. Takeuchi, T. Takahashi, and D. Inoue, “*Dark-TRACER*: Early Detection Framework for Malware Activity Based on Anomalous Spatiotemporal Patterns,” *IEEE ACCESS*, Jan 2022. [[DOI]](https://doi.org/10.1109/ACCESS.2022.3145966) [[PDF]](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9690867) [[Related Slides]](https://drive.google.com/file/d/1IlOar4ARu-olK4k-b5g6WWC4Id2abfnB/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/) [[Codes]](https://github.com/Gotchance/Dark-TRACER)
9. B. Sun, T. Ban, **C. Han**, T. Takahashi, K. Yoshioka, J. Takeuchi, A. Sarrafzadeh, M. Qiu, and D. Inoue, “Leveraging Machine Learning Technique to Identify Deceptive Decoy Documents Associated with Targeted Email Attacks,”  *IEEE ACCESS*, May 2021. [[DOI]](https://doi.org/10.1109/ACCESS.2021.3082000) [[PDF]](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9435284)
10. **C. Han**, J. Shimamura, T. Takahashi, D. Inoue, J. Takeuchi, and K. Nakao, “Real-time Detection of Global Cyberthreat Based on Darknet by Estimating Anomalous Synchronization Using Graphical Lasso,” *IEICE Transactions on Information and Systems, Vol.E103-D, No.10*, pp.2113-2124, Oct 2020.  [[DOI]](https://doi.org/10.1587/transinf.2020EDP7076) [[PDF]](https://www.jstage.jst.go.jp/article/transinf/E103.D/10/E103.D_2020EDP7076/_pdf) [[Related Slides]](https://drive.google.com/file/d/1dIJjqipH49RewPDGlMT3LL-xODIclPqc/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)

### Refereed Conference Papers

1. J. Kim, H. Lee, S. Hong, T. Takahashi, **C. Han**, T. Morikawa, and S. Choi, “Don’t Trust the AI Ecosystem: Analyzing Privacy Leakage in Compromised Open-Source Components,” *ACM CCS*, Nov 2026. **(Tier 1)**
1. H. Lee, J. Kim, **C. Han**, G. Bang, T. Takahashi, and S. Choi, “An Empirical Study on the Privacy Effects of Model Merging in Vision Language Models,” *International Conference on Ubiquitous and Future Networks (ICUFN)*, Jul 2026.
1. K. Nikawa, **C. Han**, A. Tanaka, K. Iwamoto, T. Takahashi, and J. Takeuchi, “Improving Scalable Clustering for IoT Malware via Code Region Extraction,” *The 28th Annual International Conference on Information Security and Cryptology (ICISC)*, Nov 2025. **(Tier 3)** [[DOI]](https://doi.org/10.1007/978-981-95-8034-7_5)
1. S. Kato, **C. Han**, T. Takahashi, and K. Sakurai, “A Survey of Jailbreak Attacks and Defenses for Large Language Models,” *The International Conference on Artificial Intelligence Computing and Systems (AICompS)*, Nov 2025.
1. Y. Lee, **C. Han**, M. Peng, and T. Takahashi, “LLM-Based Multi-Label Mapping of Snort Rules to ATT&CK,” *IEEE Conference on Dependable and Secure Computing (DSC)*, Oct 2025. [[DOI]](https://doi.org/10.1109/DSC65356.2025.11260863)
1. S. Kawanaka, K. Miyamoto, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Towards Explainable Machine Learning NIDS Reflecting Cyber-Attack Characteristics,” *Workshop on Recent Advances in Resilient and Trustworthy MAchine learning-driveN systems (ARTMAN)*, Oct 2025. [[DOI]](https://doi.org/10.1145/3733821.3763023) [[PDF]](https://dl.acm.org/doi/pdf/10.1145/3733821.3763023)
2. K. Ma, **C. Han**, A. Tanaka, T. Takahashi, and J. Takeuchi, “Towards Architecture-Independent Function Call Analysis for IoT Malware,” *Information Security Conference (ISC)*, Oct 2025. **(Tier 3)** [[DOI]](https://doi.org/10.1007/978-3-032-08124-7_21)
3. K. Miyamoto, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Intrusion Detection Simplified: A Feature-free Approach to Traffic Classification Using Transformers,” *Workshop on Recent Advances in Resilient and Trustworthy MAchine learning-driveN systems (ARTMAN)*, Dec 2024. [[DOI]](https://doi.org/10.1109/ACSACW65225.2024.00011) [[PDF]](https://www.researchgate.net/publication/389970359_Intrusion_Detection_Simplified_A_Feature-free_Approach_to_Traffic_Classification_Using_Transformers) [[Slides]](https://drive.google.com/file/d/12UUJAAm3IaptqfdMFzANn0mBJNbbzuXp/view?usp=sharing)
6. **C. Han**, A. Tanaka, T. Takahashi, S. Dadkhah, A. Ghorbani, and T. Lin, “Traceability Measurement Analysis of Sustained Internet-Wide Scanners via Darknet,” *IEEE Conference on Dependable and Secure Computing (DSC)*, Nov 2024. [[DOI]](https://doi.org/10.1109/DSC63325.2024.00015) [[PDF]](https://www.researchgate.net/publication/386267696_Traceability_Measurement_Analysis_of_Sustained_Internet-Wide_Scanners_via_Darknet) [[Slides]](https://drive.google.com/file/d/1WUWhQFSaON_GG-3VMm1H59b-wWucyDz1/view?usp=sharing)
7. K. Nikawa, **C. Han**, A. Tanaka, K. Iwamoto, T. Takahashi, and J. Takeuchi, “Poster: Analyzing the Impact of User Code and Library Functions for Improving IoT Malware Clustering,” *IEEE Conference on Dependable and Secure Computing (DSC)*, Nov 2024. [[Poster]](https://drive.google.com/file/d/18A6LgyDNLd29NpQJ9K3anLnjsWZJlRh-/view?usp=sharing)
8. S. Kawanaka, K. Miyamoto, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Poster: From Packets to Explanation: Enhancing NIDS with XAI and Cyber-Attack Analysis,” *IEEE Conference on Dependable and Secure Computing (DSC)*, Nov 2024. [[Poster]](https://drive.google.com/file/d/1FHDhxnDv8iU5uSBD0VTIsZ6xLe6Rw6Z5/view?usp=sharing)
9. S. Kawanaka, Y. Kashiwabara, K. Miyamoto, M. Iida, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Packet-Level Intrusion Detection Using LSTM Focusing on Personal Information and Payloads,” *Asia Joint Conference on Information Security (AsiaJCIS)*, Aug 2023. [[DOI]](https://doi.org/10.1109/AsiaJCIS60284.2023.00024) [[PDF]](https://www.researchgate.net/publication/376978134_Packet-Level_Intrusion_Detection_Using_LSTM_Focusing_on_Personal_Information_and_Payloads) [[Slides]](https://drive.google.com/file/d/1FaZuALLXTlxgpgg7WGFqOvi-zcSLzsqH/view?usp=sharing)
10. K. Oshio, S. Takada, T. He, **C. Han**, A. Tanaka, T. Takahashi, and J. Takeuchi, “Towards Functional Analysis of IoT Malware Using Function Call Sequence Graphs and Clustering,” *IEEE Annual Computers, Software, and Applications Conference (COMPSAC)*, Jun 2023. [[DOI]](https://doi.org/10.1109/COMPSAC57700.2023.00239) [[PDF]](https://www.researchgate.net/publication/372864827_Towards_Functional_Analysis_of_IoT_Malware_Using_Function_Call_Sequence_Graphs_and_Clustering) [[Slides]](https://drive.google.com/file/d/1PPvqpM4K3Nkc6a9phedLOrDDbfVmXOZ1/view?usp=sharing)
11. T. He, **C. Han**, A. Tanaka, T. Takahashi, and J. Takeuchi, “Work in Progress: New Seed Set Selection Method of the Scalable Method for Constructing Phylogenetic Trees,” *ACM International Conference on Computing Frontiers (CF)*, May 2023. [[DOI]](https://doi.org/10.1145/3587135.3592820) [[PDF]](https://www.researchgate.net/publication/372930489_Work_in_Progress_New_Seed_Set_Selection_Method_of_the_Scalable_Method_for_Constructing_Phylogenetic_Trees) [[Slides]](https://drive.google.com/file/d/1urhhi1yJp_02dPAa_-uPCLtwoSmJGZOy/view?usp=sharing)
12. M. Iida, K. Miyamoto, S. Kawanaka, Y. Takeishi, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Multimodal Feature Integration for High-Accuracy Network Intrusion Detection,” *International Conference on Computer Applications and Information Security (ICCAIS)*, Mar 2023. [[Slides]](https://drive.google.com/file/d/1Q1qWoZjeAneXLTJomlhnYw-Wam6RRNzf/view?usp=sharing)
13. **C. Han**, A. Tanaka, J. Takeuchi, T. Takahashi, T. Morikawa, and T. Lin, “Towards Long-Term Continuous Tracing of Internet-Wide Scanning Campaigns Based on Darknet Analysis,” *International Conference on Information Systems Security and Privacy (ICISSP)*, Feb 2023. [[DOI]](https://doi.org/10.5220/0011769300003405) [[PDF]](https://www.researchgate.net/publication/369018254_Towards_Long-Term_Continuous_Tracing_of_Internet-Wide_Scanning_Campaigns_Based_on_Darknet_Analysis) [[Poster]](https://drive.google.com/file/d/1ai1mrLnSdTMXcB16utr4SJAVR4njhGHZ/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)


17. **C. Han**, A. Tanaka, and T. Takahashi, “Darknet Analysis-Based Early Detection Framework for Malware Activity: Issue and Potential Extension,” *IEEE International Conference on Big Data*, Dec 2022. [[DOI]](https://doi.org/10.1109/BigData55660.2022.10021021) [[PDF]](https://www.researchgate.net/publication/367467291_Darknet_Analysis-Based_Early_Detection_Framework_for_Malware_Activity_Issue_and_Potential_Extension) [[Slides]](https://drive.google.com/file/d/1ORDkdILvprY8D2wCTP49_lfTWglJh5SJ/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)
7. K. Oshio, S. Takada, **C. Han**, A. Tanaka, and J. Takeuchi, “Poster: Flexible Function Estimation of IoT Malware Using Graph Embedding Technique,” *IEEE Symposium on Computers and Communications (ISCC)*, Jun 2022. [[DOI]](https://doi.org/10.1109/ISCC55528.2022.9912475) [[PDF]](https://www.researchgate.net/publication/365112136_Poster_Flexible_Function_Estimation_of_IoT_Malware_Using_Graph_Embedding_Technique) [[Poster]](https://drive.google.com/file/d/1VXEkAuXN9_SCL5mKY16S2oT_xb80e-D8/view?usp=sharing)
8. K. Miyamoto, H. Goto, R. Ishibashi, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Malicious Packet Classification Based on Neural Network Using Kitsune Features,” *Proceedings of the 2nd International Conference on Intelligent Systems and Pattern Recognition*, Springer, Jun 2022. [[DOI]](https://doi.org/10.1007/978-3-031-08277-1_25) [[PDF]](https://www.researchgate.net/publication/361364873_Malicious_Packet_Classification_Based_on_Neural_Network_Using_Kitsune_Features) [[Slides]](https://drive.google.com/file/d/1ZU98xh9WhpJLksvVZJtiMt_Zg4vVuO7-/view?usp=sharing)
9. A. Tanaka, **C. Han**, T. Takahashi, and K. Fujisawa, “Internet-Wide Scanner Fingerprint Identifier Based on TCP/IP Header,” *The 6th International Conference on Fog and Mobile Edge Computing (FMEC)*, IEEE, 2021. [[DOI]](https://doi.org/10.1109/FMEC54266.2021.9732414) [[PDF]](https://www.researchgate.net/publication/359273162_Internet-Wide_Scanner_Fingerprint_Identifier_Based_on_TCPIP_Header) [[Slides]](https://drive.google.com/file/d/1GJ1Fsosu54WIzxX0nJY1oKQTV2n_xeev/view?usp=sharing)
2. T. He, **C. Han**, T. Takahashi, S. Kijima, and J. Takeuchi, “Scalable and Fast Hierarchical Clustering of IoT Malware Using Active Data Selection,” *The 6th International Conference on Fog and Mobile Edge Computing (FMEC)*, IEEE, 2021. [[DOI]](https://doi.org/10.1109/FMEC54266.2021.9732550) [[PDF]](https://www.researchgate.net/publication/359273244_Scalable_and_Fast_Hierarchical_Clustering_of_IoT_Malware_Using_Active_Data_Selection) [[Slides]](https://drive.google.com/file/d/19-ntZMuONwAQN_sj85MVArDsJhObrxAu/view?usp=sharing)
7. **C. Han**, J. Takeuchi, T. Takahashi, and D. Inoue, “Automated Detection of Malware Activities Using Nonnegative Matrix Factorization,” *IEEE International Conference on Trust, Security and Privacy in Computing and Communications (TrustCom)*, Oct 2021. **(Tier 3)** [[DOI]](https://doi.org/10.1109/TrustCom53373.2021.00085) [[PDF]](https://www.researchgate.net/publication/359121104_Automated_Detection_of_Malware_Activities_Using_Nonnegative_Matrix_Factorization) [[Slides]](https://drive.google.com/file/d/1UvKEEXsir7X_Vx7puhVCI8V9hpsvxS0O/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)
8. R. Ishibashi, H. Goto, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Which Packet Did They Catch? Associating NIDS Alerts with Their Communication Sessions,” *Asia Joint Conference on Information Security (AsiaJCIS)*, 2021. [[DOI]](https://doi.org/10.1109/AsiaJCIS53848.2021.00012) [[PDF]](https://www.researchgate.net/publication/354887287_Which_Packet_Did_They_Catch_Associating_NIDS_Alerts_with_Their_Communication_Sessions) [[Slides]](https://drive.google.com/file/d/1WSmsCvpRJ2spJIaBS2sIWdYf6bAt5_wp/view?usp=sharing)
9. K. Masumi, **C. Han**, T. Ban, and T. Takahashi, “Poster: Towards Efficient Labeling of Network Incident Datasets Using Tcpreplay and Snort,” *ACM Conference on Data and Application Security and Privacy (CODASPY)*, 2021. [[DOI (include video)]](https://doi.org/10.1145/3422337.3450326) [[PDF]](https://www.researchgate.net/publication/351102418_Towards_Efficient_Labeling_of_Network_Incident_Datasets_Using_Tcpreplay_and_Snort) [[Poster]](https://drive.google.com/file/d/1dZnXrom8q0XXsHM9bqVuRiJgrWWhIy_r/view?usp=sharing)
10. T. Takahashi, Y. Umemura, **C. Han**, T. Ban, K. Furumoto, O. Nakamura, K. Yoshioka, J. Takeuchi, N. Murata, and Y. Shiraishi, “Designing Comprehensive Cyber Threat Analysis Platform: Can We Orchestrate Analysis Engines?,” *IEEE International Conference on Pervasive Computing and Communications Workshops and other Affiliated Events (PerCom Workshops)*, pp.376-379, 2021. [[DOI]](https://doi.org/10.1109/PerComWorkshops51409.2021.9431125) [[PDF]](https://www.researchgate.net/publication/351829861_Designing_Comprehensive_Cyber_Threat_Analysis_Platform_Can_We_Orchestrate_Analysis_Engines) [[Slides]](https://drive.google.com/file/d/1I2loykY-R08cr3ePeAGHWzP5rPPLNBQU/view?usp=sharing)
11. R. Kawasoe, **C. Han**, R. Isawa, T. Takahashi, and J. Takeuchi, “Investigating Behavioral Differences between IoT Malware via Function Call Sequence Graphs,” *Proceedings of the 36th ACM/SIGAPP Symposium on Applied Computing (SAC)*, 2021. **(Tier 3)** (Acceptance rate: 24.9%) [[DOI]](https://doi.org/10.1145/3412841.3442041) [[PDF]](https://dl.acm.org/doi/pdf/10.1145/3412841.3442041) [[Slides]](https://drive.google.com/file/d/1eesRVIp0WTFu3iEcfAkdzEXRkx3WeRAm/view?usp=sharing)
1. T. He, **C. Han**, R. Isawa, T. Takahashi, S. Kijima, J. Takeuchi, and K. Nakao, “A Fast Algorithm for Constructing Phylogenetic Trees with Application to IoT Malware Clustering,” *Neural Information Processing - 26rd International Conference (ICONIP)*, 2019. (Acceptance rate: 27.4%) [[DOI]](https://doi.org/10.1007/978-3-030-36708-4_63) [[PDF]](https://www.researchgate.net/publication/337922580_A_Fast_Algorithm_for_Constructing_Phylogenetic_Trees_with_Application_to_IoT_Malware_Clustering) [[Slides]](https://drive.google.com/file/d/1gITKqvXhNPeqG8sPya09vwsd4hRGK4zz/view?usp=sharing)
2. **C. Han**, J. Shimamura, T. Takahashi, D. Inoue, M. Kawakita, J. Takeuchi, and K. Nakao, “Real-Time Detection of Malware Activities by Analyzing Darknet Traffic Using Graphical Lasso,” *IEEE International Conference on Trust, Security and Privacy in Computing and Communications (TrustCom): Security Track*, 2019. **(Tier 3)** (Acceptance rate 28.67%=82/286) [[DOI]](https://doi.org/10.1109/TrustCom/BigDataSE.2019.00028) [[PDF]](https://www.researchgate.net/publication/336946818_Real-Time_Detection_of_Malware_Activities_by_Analyzing_Darknet_Traffic_Using_Graphical_Lasso) [[Slides]](https://drive.google.com/file/d/1dIJjqipH49RewPDGlMT3LL-xODIclPqc/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)
3. **C. Han**, K. Kono, M. Kawakita, and J. Takeuchi, “Botnet Detection Using Graphical Lasso with Graph Density,” *Neural Information Processing - 23rd International Conference (ICONIP), vol.9947*, pp.537-545, 2016. [[DOI]](https://doi.org/10.1007/978-3-319-46687-3_59) [[PDF]](https://www.researchgate.net/publication/309176434_Botnet_Detection_Using_Graphical_Lasso_with_Graph_Density) [[Slides]](https://drive.google.com/file/d/1QbywuJC7g0pKLfpLqaSbuQqQSXPYW40M/view?usp=sharing)


<hr>
### Non-refereed Domestic Conference Papers

1. K. Ma, **C. Han**, A. Tanaka, T. Takahashi, and J. Takeuchi, “Removing obstacles to function call analysis in IoT malware,” *Symposium on Cryptography and Information Security (SCIS2025)*, Jan 2025. [[Slides (in Japanese)]](https://drive.google.com/file/d/1i_rbRpaJP2xOZfzmEwwv9-3ui_OK-wmY/view?usp=sharing)
2. S. Kawanaka, K. Miyamoto, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Investigating the Factors Influencing Cyber-Attack Detection in NIDS Using Explainable AI,” *Symposium on Cryptography and Information Security (SCIS2025)*, Jan 2025. [[Slides (in Japanese)]](https://drive.google.com/file/d/1DzhHm1P3drSL59LMFM9CWAXgqRj--_00/view?usp=sharing)
3. K. Ma, **C. Han**, A. Tanaka, T. Takahashi, and J. Takeuchi, “Study of Graphing Methods for Functional Analysis of IoT Malware Using Function Call Sequence Graphs,” *Computer Security Symposium (CSS2024)*, Oct 2024. [[Slides (in Japanese)]](https://drive.google.com/file/d/1Qr1ONg_9mDc82YWU53S20DMaYv_d5tBZ/view?usp=sharing)
4. K. Nikawa, **C. Han**, A. Tanaka, K. Iwamoto, T. Takahashi, and J. Takeuchi, “Improvement of Distance Definition for In-Depth Functional Analysis in Phylogenetic Clustering of IoT Malware,” *Computer Security Symposium (CSS2024)*, Oct 2024. [[Slides (in Japanese)]](https://drive.google.com/file/d/1O2RTE2Qg2ZIBiEyvRolfheBJ9g3msdqC/view?usp=sharing)
5. S. Akabane, **C. Han**, K. Iwamoto, R. Isawa, T. Takahashi, and D. Inoue, “Identification of User-Defined Functions Based on Function Call Transition,” *104th CSEC*, Mar 2024. [[Slides (in Japanese)]](https://drive.google.com/file/d/1sgZUehT_uujIwOrAPoyVrs_G3RF-l_sK/view?usp=sharing)
6. **C. Han**, A. Tanaka, and T. Takahashi, “Study on Cluster Traceability of Internet-Wide Scanners,” *Computer Security Symposium (CSS2023)*, Oct 2023. [[Slides (in Japanese)]](https://drive.google.com/file/d/1B7vr-Nw5HLVZ0GeJBvtO0KZnPYFmZsEE/view?usp=sharing)
7. K. Miyamoto, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “An early and successive traffic classification based on packet-level features and prediction,” *Computer Security Symposium (CSS2023)*, Oct 2023. [[Slides (in Japanese)]](https://drive.google.com/file/d/1d_dwSs4EKPKMGn68AY2AjMqn8iFU6HZu/view?usp=sharing)
8. M. Iida, K. Miyamoto, Y. Takeishi, S. Kawanaka, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Multimodal Feature Integration Toward High-Accuracy Network Intrusion Detection,” *IEICE Tech. Rep., vol.122, no.422,  ICSS2022-55*, pp.43-48, Mar 2023. [[Slides (in Japanese)]](https://drive.google.com/file/d/1XsXcgWFvKR2LK1KzLaVRJlT1VYVJJHuL/view?usp=sharing)
9. Y. Kashiwabara, K. Miyamoto, M. Iida, S. Kawanaka, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Consideration of a Packet Level Anomaly Communication Classification Model Using Word Embedding and LSTM,” *IEICE Tech. Rep., vol.122, no.422,  ICSS2022-53*, pp.31-36, Mar 2023. [[Slides (in Japanese)]](https://drive.google.com/file/d/1J9Agdh2n1aKLUpBZCqx9yDLoRabh6df1/view?usp=sharing)


10. **C. Han**, A. Tanaka, T. Takahashi, and J. Takeuchi, “Tracing Methodology for Scanning Campaigns Based on Darknet Analysis,” *IEICE Tech. Rep., vol.122, no.244, ICSS2022-43*, pp.31-36, Nov 2022. [[Slides (in Japanese)]](https://drive.google.com/file/d/1wB1Jh2Ft_sVIpevXUg8ROOSnQz89FKDJ/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)
7. **C. Han**, A. Tanaka, and T. Takahashi, “Study on Validation and Future Extension of Early Detection Framework for Malware Activities Based on Darknet Analysis,” *Computer Security Symposium (CSS2022)*, Oct 2022. [[Slides (in Japanese)]](https://drive.google.com/file/d/1NExxRpbl0kvS2hMtldCZikUX0PzLSP0G/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)
8. A. Tanaka, **C. Han**, and T. Takahashi, “Destination Port Set Analysis via Internet-Wide Scanner Fingerprint,” *Computer Security Symposium (CSS2022)*, Oct 2022. [[Slides (in Japanese)]](https://drive.google.com/file/d/1CfIvloo8aJYCiehmD0X5MWSPcS7wnO_L/view?usp=sharing)
9. T. He, **C. Han**, A. Tanaka, T. Takahashi, and J. Takeuchi, “Implement and evaluation of the online processing algorithm for scalable malware clustering based on the phylogenetic tree,” *Computer Security Symposium (CSS2022)*, Oct 2022. [[Slides (in Japanese)]](https://drive.google.com/file/d/14KCrd5KMQc4vDWNBOL2KC2rvhgvZqH5u/view?usp=sharing)
10. K. Miyamoto, Y. Takeishi, M. Iida, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Network Traffic Classification: Go from Packet Level to Session Level,” *Computer Security Symposium (CSS2022)*, Oct 2022. [[Slides (in Japanese)]](https://drive.google.com/file/d/1iDFSbpYqtPcP_FPrNThEI7EcerelYMTi/view?usp=sharing)
11. S. Takada, T. He, **C. Han**, A. Tanaka, and J. Takeuchi, “Behavior Analysis of IoT Malware Using Function Call Sequence Graphs and Clustering,” *IEICE Tech. Rep., vol.121, no.410, ICSS2021-77*, pp.111-116, Mar 2022. [[Slides (in Japanese)]](https://drive.google.com/file/d/1m-XomDwPPvQYcD9Ag4-KFz7C0fGABXm-/view?usp=sharing)
9. **C. Han**, J. Takeuchi, T. Takahashi, and D. Inoue, “Study on the Early Detection Framework for Malware Activity Based on Anomalous Synchronization Estimation,” *Computer Security Symposium (CSS2021)*, Oct 2021. [[Slides (in Japanese)]](https://drive.google.com/file/d/13yc8xgMuI1mjBJRXKnC6GxDxI33aIdOV/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)
7. A. Tanaka, **C. Han**, T. Takahashi, and K. Fujisawa, “Proposing a Genetic Algorithm Approach for Unveiling Fingerprint of Internet-Wide Scanner,” *Computer Security Symposium (CSS2021)*, Oct 2021. **CSS Best Student Paper Award** [[Slides (in Japanese)]](https://drive.google.com/file/d/1CXBqSGTiO8OX9GWZh5SMCOIUI0Y3xgU2/view?usp=sharing)
8. T. He, **C.Han**, T. Takahashi, S. Kijima, and J. Takeuchi, “Malware Hierarchical Clustering Applying Active Learning,” *Computer Security Symposium (CSS2021)*, Oct 2021. [[Slides (in Japanese)]](https://drive.google.com/file/d/1oIoNFbd_FS-ghi12RHe99hgDRXx9F_XU/view?usp=sharing)
9. S. Takada, R. Kawasoe, T. He, **C. Han**, A. Tanaka, and J. Takeuchi, “Study on Improvement of Function Estimation Method of IoT Malware Using Graph Embedding,” *Computer Security Symposium (CSS2021)*, Oct 2021. [[Slides (in Japanese)]](https://drive.google.com/file/d/167LTZOfNkfoMNeotsY3K697jYBQpBJdq/view?usp=sharing)
10. K. Miyamoto, H. Goto, R. Ishibashi, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Malicious Packet Classification Using Kitsune Features,” *Computer Security Symposium (CSS2021)*, Oct 2021. [[Slides (in Japanese)]](https://drive.google.com/file/d/1TQx3Adr1GMZMYDk1ZYo8gCXdEVIFk-_x/view?usp=sharing)
11. T. He, **C. Han**, R. Isawa, T. Takahashi, S. Kijima, and J. Takeuchi, “An Evaluation of Scalable Clustering in Fast Construction Algorithm of Phylogenetic Tree,” *IEICE Tech. Rep., vol.120, no.384, ICSS2020-38*, pp.72-77, Mar 2021. [[Slides (in Japanese)]](https://drive.google.com/file/d/1LeW2lXccer54Im5FQykTu75CT_iN2tj4/view?usp=sharing)
12. R. Kawasoe, **C. Han**, R. Isawa, T. Takahashi, and J. Takeuchi, “Improvement of Functional Difference Investigation Method and Analyzing for Clusters of IoT Malware,” *IEICE Tech. Rep., vol.120, no.384, ICSS2020-39*, pp.78-83, Mar 2021. [[Slides (in Japanese)]](https://drive.google.com/file/d/1cVK5f-suLwQ_gDW9rw3oPwgMjMMyXGVD/view?usp=sharing)
13. R. Ishibashi, H. Goto, **C. Han**, T. Ban, T. Takahashi, and J. Takeuchi, “Developing and Characterizing a New Approach to Extracting Communication Sessions Associated with NIDS Alerts,” *IEICE Tech. Rep., vol.120, no.384, ICSS2020-26*, pp.1-6, Mar 2021. [[Slides (in Japanese)]](https://drive.google.com/file/d/1wOrsGtVpIIhyfNYQn1-MzTFfGbPXafmA/view?usp=sharing)
14. **C. Han**, J. Takeuchi, T. Takahashi, and D. Inoue, “Evaluation of Malware Activity Detection Method Using Nonnegative Matrix Factorization,” *Symposium on Cryptography and Information Security (SCIS2021)*, Jan 2021. [[Slides (in Japanese)]](https://drive.google.com/file/d/1XszA9pQDcO-FgvN-KFeRO2uU8oLfNX8C/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)
1. R. Kawasoe, **C. Han**, R. Isawa, T. Takahashi, and J. Takeuchi, “A Feasibility Study on Investigating Functional Differences between IoT Malware,” *Computer Security Symposium (CSS2020)*, Oct 2020. [[Slides (in Japanese)]](https://drive.google.com/file/d/1DIFyjaLyzT2dbKcX1pBIttQHclu26aBj/view?usp=sharing)
1. R. Kawasoe, **C. Han**, R. Isawa, T. Takahashi, and J. Takeuchi, “A Study on Function Estimation of IoT Malware Focusing on Function Call Sequence,” *Symposium on Cryptography and Information Security (SCIS2020)*, Jan 2020. [[Slides (in Japanese)]](https://drive.google.com/file/d/1hIucksOE7IyocdLz5k7KoTW2pus5JVd3/view?usp=sharing)
1. T. He, **C. Han**, R. Isawa, T. Takahashi, S. Kijima, J. Takeuchi, and K. Nakao, “A Fast Algorithm for Constructing Phylogenetic Trees and Its Evaluation,” *IEICE Tech. Rep., vol.119, no.288, ICSS2019-61*, pp.7-12, Nov 2019. [[Slides (in Japanese)]](https://drive.google.com/file/d/1VZy3EcXSG_Q-jlkikofLuAn-_BdI7LcU/view?usp=sharing)
1. Y. Nakagawa, **C. Han**, J. Shimamura, T. Takahashi, A. Fujita, K. Yoshioka, and D. Inoue, “An Investigation of Constant Internet-Wide Scanning through Analysis of Darknet Traffic,” *Computer Security Symposium (CSS2019)*, Oct 2019. [[Slides (in Japanese)]](https://drive.google.com/file/d/1gcIzE0_Isg0pOiihvU-Dfx0R2v2dEsPK/view?usp=sharing)
1. **C. Han**, J. Shimamura, T. Takahashi, D. Inoue, J. Takeuchi, and K. Nakao, “Evaluation of Cyber Attack Detection Method based on Darknet Traffic Analysis,” *Symposium on Cryptography and Information Security (SCIS2019)*, Jan 2019. [[Slides (in Japanese)]](https://drive.google.com/file/d/1snxK6ZKIKzCPa6_OtI0-TU4kFDS3CEuU/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)
1. **C. Han**, J. Shimamura, T. Takahashi, D. Inoue, M. Kawakita, J. Takeuchi, and K. Nakao, “A Study on Malware Activity Detection Based on Real-time Analysis of Darknet Data Using Graphical Lasso,” *IEICE Tech. Rep., vol.117, no.481, ICSS2017-51*, pp.1-6, Mar 2018. [[Slides (in Japanese)]](https://drive.google.com/file/d/1Skr58QPau27t5mFn_wJTFaFgyQW5iUPP/view?usp=sharing)
1. **C. Han**, S. Matsumoto, J. Kawamoto, and K. Sakurai, “Classified by the API call record and personal information leakage detection of Android malware,” *Hinokuni - Land of Fire Information Processing Symposium, 3A-4*, 2016. [[Slides (in Japanese)]](https://drive.google.com/file/d/1MFJlulvPfX_7fJc5s9IUMje8uLA5z0qJ/view?usp=sharing)



<details class="cv-details">
<summary>In Japanese (Non-refereed Domestic Conference Papers)</summary>
<div>


1. 馬権聖, **韓燦洙**, 田中智, 高橋健志, 竹内純一, “IoTマルウェアにおける関数呼び出し分析の阻害要因の除去,” *暗号と情報セキュリティシンポジウム (SCIS2025)*, 2025年1月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1i_rbRpaJP2xOZfzmEwwv9-3ui_OK-wmY/view?usp=sharing)
1. 川中翔太, 宮本耕平, **韓燦洙**, 班涛, 高橋健志, 竹内純一, “説明可能AIを用いたNIDSにおけるサイバー攻撃検出要因の調査,” *暗号と情報セキュリティシンポジウム (SCIS2025)*, 2025年1月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1DzhHm1P3drSL59LMFM9CWAXgqRj--_00/view?usp=sharing)
1. 馬権聖, **韓燦洙**, 田中智, 高橋健志, 竹内純一, “関数呼び出し時系列グラフを用いたIoTマルウェアの機能分析のためのグラフ作成手法の検討,” *コンピュータセキュリティシンポジウム2024 (CSS2024)*, 2024年10月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1Qr1ONg_9mDc82YWU53S20DMaYv_d5tBZ/view?usp=sharing)
1. 二川功佑, **韓燦洙**, 田中智, 岩本一樹, 高橋健志, 竹内純一, “IoTマルウェアの系統樹クラスタリングにおける機能面に踏み込んだ解析のための距離定義の改良,” *コンピュータセキュリティシンポジウム2024 (CSS2024)*, 2024年10月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1O2RTE2Qg2ZIBiEyvRolfheBJ9g3msdqC/view?usp=sharing)
1. 赤羽秀, **韓燦洙**, 岩本一樹, 伊沢亮一, 高橋健志, 井上大介, “関数呼び出しの推移に基づいたユーザ定義関数の特定,” *第104回 コンピュータセキュリティ研究会 (CSEC)*, 2024年3月 **CSEC優秀研究賞** [[Slides (in Japanese)]](https://drive.google.com/file/d/1sgZUehT_uujIwOrAPoyVrs_G3RF-l_sK/view?usp=sharing)
1. **韓燦洙**, 田中智, 高橋健志, “インターネットスキャナのクラスタ追跡可能性評価,” *コンピュータセキュリティシンポジウム2023 (CSS2023)*, 2023年10月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1B7vr-Nw5HLVZ0GeJBvtO0KZnPYFmZsEE/view?usp=sharing)
1. 宮本耕平, **韓燦洙**, 班涛, 高橋健志, 竹内純一, “パケット単位の特徴量に基づいた通信の逐次的な早期分類,” *コンピュータセキュリティシンポジウム2023 (CSS2023)*, 2023年10月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1d_dwSs4EKPKMGn68AY2AjMqn8iFU6HZu/view?usp=sharing)
1. 飯田昌澄, 宮本耕平, 武石啓成, 川中翔太, **韓燦洙**, 班涛, 高橋健志, 竹内純一, “高精度なネットワーク侵入検知のための特徴量の統合,” *信学技報, vol.122, no.422, ICSS2022-55*, pp.43-48, 2023年3月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1XsXcgWFvKR2LK1KzLaVRJlT1VYVJJHuL/view?usp=sharing)
1. 柏原芳克, 宮本耕平, 飯田昌澄, 川中翔太, **韓燦洙**, 班涛, 高橋健志, 竹内純一, “単語埋め込みとLSTMを用いたパケット単位異常通信分類モデルに関する考察,” *信学技報, vol.122, no.422, ICSS2022-53*, pp.31-36, 2023年3月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1J9Agdh2n1aKLUpBZCqx9yDLoRabh6df1/view?usp=sharing)
1. **韓燦洙**, 田中智, 高橋健志, 竹内純一, “ダークネット解析に基づくスキャンキャンペーンの追跡手法の提案,” *信学技報, vol.122, no.244, ICSS2022-43*, pp.31-36, 2022年11月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1wB1Jh2Ft_sVIpevXUg8ROOSnQz89FKDJ/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)
1. **韓燦洙**, 田中智, 高橋健志, “ダークネット解析に基づくマルウェア活動の早期検知フレームワークの有効性の検証と今後の拡張,” *コンピュータセキュリティシンポジウム2022 (CSS2022)*, 2022年10月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1NExxRpbl0kvS2hMtldCZikUX0PzLSP0G/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/)
1. 田中智, **韓燦洙**, 高橋健志, “フィンガープリントを用いたスキャナの分類及び宛先ポートセットの分析,” *コンピュータセキュリティシンポジウム2022 (CSS2022)*, 2022年10月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1CfIvloo8aJYCiehmD0X5MWSPcS7wnO_L/view?usp=sharing)
1. 何天祥, **韓燦洙**, 田中智, 高橋健志, 竹内純一, “系統樹に基づくスケーラブルなマルウェアクラスタリングのオンライン処理手法の実装と評価,” *コンピュータセキュリティシンポジウム2022 (CSS2022)*, 2022年10月. [[Slides (in Japanese)]](https://drive.google.com/file/d/14KCrd5KMQc4vDWNBOL2KC2rvhgvZqH5u/view?usp=sharing)
1. 宮本耕平, 武石啓成, 飯田昌澄, **韓燦洙**, 班涛, 高橋健志, 竹内純一, “パケット単位分類に基いたセッション単位での通信分類,” *コンピュータセキュリティシンポジウム2022 (CSS2022)*, 2022年10月. [[Slides (in Japanese)]](https://drive.google.com/file/d/1iDFSbpYqtPcP_FPrNThEI7EcerelYMTi/view?usp=sharing)
1. 高田智史, 何天祥, **韓燦洙**, 田中智, 竹内純一, “関数呼び出しシーケンスグラフとクラスタリングを用いたIoTマルウェアの機能分析,” *信学技報, vol.121, no.410, ICSS2021-77*, pp.111-116, 2022年3月. [[Slides]](https://drive.google.com/file/d/1m-XomDwPPvQYcD9Ag4-KFz7C0fGABXm-/view?usp=sharing)
1. **韓燦洙**, 竹内純一, 高橋健志, 井上大介, “異常同期性推定に基づくマルウェア活動の早期検知フレームワークの検討,” *コンピュータセキュリティシンポジウム2021 (CSS2021)*, 2021年10月. [[Slides]](https://drive.google.com/file/d/13yc8xgMuI1mjBJRXKnC6GxDxI33aIdOV/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/index.ja.html)
1. 田中智, **韓燦洙**, 高橋健志, 藤澤克樹, “遺伝的アルゴリズムに基づいた広域スキャンのフィンガープリント特定技術の提案,” *コンピュータセキュリティシンポジウム2021 (CSS2021)*, 2021年10月. **CSS学生論文賞** [[Slides]](https://drive.google.com/file/d/1CXBqSGTiO8OX9GWZh5SMCOIUI0Y3xgU2/view?usp=sharing)
1. 何天祥, **韓燦洙**, 高橋健志, 来嶋秀治, 竹内純一, “能動学習に基づいたマルウェア階層的クラスタリング,” *コンピュータセキュリティシンポジウム2021 (CSS2021)*, 2021年10月. [[Slides]](https://drive.google.com/file/d/1oIoNFbd_FS-ghi12RHe99hgDRXx9F_XU/view?usp=sharing)
1. 高田智史, 川添玲雄, 何天祥, **韓燦洙**, 田中智, 竹内純一, “グラフ埋め込みを用いたIoTマルウェアの機能推定手法の改善の検討,” *コンピュータセキュリティシンポジウム2021 (CSS2021)*, 2021年10月. [[Slides]](https://drive.google.com/file/d/167LTZOfNkfoMNeotsY3K697jYBQpBJdq/view?usp=sharing)
1. 宮本耕平, 後藤大輝, 石橋亮典, **韓燦洙**, 班涛, 高橋健志, 竹内純一, “Kitsune特徴量を用いた悪性通信のパケット分類,” *コンピュータセキュリティシンポジウム2021 (CSS2021)*, 2021年10月. [[Slides]](https://drive.google.com/file/d/1TQx3Adr1GMZMYDk1ZYo8gCXdEVIFk-_x/view?usp=sharing)
1. 何天祥, **韓燦洙**, 伊沢亮一, 高橋健志, 来嶋秀治, 竹内純一, “高速な系統樹構成アルゴリズムにおけるスケーラブルなクラスタリング評価,” *信学技報, vol.120, no.384, ICSS2020-38*, pp.72-77, 2021年3月. [[Slides]](https://drive.google.com/file/d/1LeW2lXccer54Im5FQykTu75CT_iN2tj4/view?usp=sharing)
2. 川添玲雄, **韓燦洙**, 伊沢亮一, 高橋健志, 竹内純一, “IoTマルウェアの機能差分調査手法の改善及びクラスタに対する分析,” *信学技報, vol.120, no.384, ICSS2020-39*, pp.78-83, 2021年3月. [[Slides]](https://drive.google.com/file/d/1cVK5f-suLwQ_gDW9rw3oPwgMjMMyXGVD/view?usp=sharing)
3. 石橋亮典, 後藤大輝, **韓燦洙**, 班涛, 高橋健志, 竹内純一, “NIDSアラートに対する原因通信の抽出手法の提案及び考察,” *信学技報, vol.120, no.384, ICSS2020-26*, pp.1-6, 2021年3月. [[Slides]](https://drive.google.com/file/d/1wOrsGtVpIIhyfNYQn1-MzTFfGbPXafmA/view?usp=sharing)
4. **韓燦洙**, 竹内純一, 高橋健志, 井上大介, “非負値行列因子分解を用いたマルウェア活動検知手法の評価,” *2021年暗号と情報セキュリティシンポジウム (SCIS2021)*, 2021年1月. [[Slides]](https://drive.google.com/file/d/1XszA9pQDcO-FgvN-KFeRO2uU8oLfNX8C/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/index.ja.html)
5. 川添玲雄, **韓燦洙**, 伊沢亮一, 高橋健志, 竹内純一, “関数呼び出しシーケンスに着目したIoTマルウェアの機能差分調査,” *コンピュータセキュリティシンポジウム2020 (CSS2020)*, 2020年10月. [[Slides]](https://drive.google.com/file/d/1DIFyjaLyzT2dbKcX1pBIttQHclu26aBj/view?usp=sharing)
6. 川添玲雄, **韓燦洙**, 伊沢亮一, 高橋健志, 竹内純一, “関数呼び出しシーケンスに着目したIoTマルウェアの機能推定に関する考察,” *2020年暗号と情報セキュリティシンポジウム (SCIS2020)*, 2020年1月. [[Slides]](https://drive.google.com/file/d/1hIucksOE7IyocdLz5k7KoTW2pus5JVd3/view?usp=sharing)
7. 何天祥, **韓燦洙**, 伊沢亮一, 高橋健志, 来嶋秀治, 竹内純一, 中尾康二, “高速な系統樹構成アルゴリズムの提案及びその評価,” *信学技報, vol.119, no.288, ICSS2019-61*, pp.7-12, 2019年11月. [[Slides]](https://drive.google.com/file/d/1VZy3EcXSG_Q-jlkikofLuAn-_BdI7LcU/view?usp=sharing)
8. 中川雄太, **韓燦洙**, 島村隼平, 高橋健志, 藤田彬, 吉岡克成, 井上大介, “ダークネットトラフィックの分析に基づく継続的な広域ネットワークスキャンの調査,” *コンピュータセキュリティシンポジウム2019 (CSS2019)*, 2019年10月. [[Slides]](https://drive.google.com/file/d/1gcIzE0_Isg0pOiihvU-Dfx0R2v2dEsPK/view?usp=sharing)
9. **韓燦洙**, 島村隼平, 高橋健志, 井上大介, 竹内純一, 中尾康二, “ダークネットトラフィック分析に基づくサイバー攻撃検知手法の評価,” *2019年暗号と情報セキュリティシンポジウム (SCIS2019)*, 2019年1月. [[Slides]](https://drive.google.com/file/d/1snxK6ZKIKzCPa6_OtI0-TU4kFDS3CEuU/view?usp=sharing) [[Datasets]](https://csdataset.nict.go.jp/darknet-2022/index.ja.html)
10. **韓燦洙**, 島村隼平, 高橋健志, 井上大介, 川喜田雅則, 竹内純一, 中尾康二, “Graphical Lassoを用いたダークネットデータのリアルタイム分析に基づくマルウェア活動検知に関する検討,” *信学技報, vol.117, no.481, ICSS2017-51*, pp.1-6, 2018年3月. [[Slides]](https://drive.google.com/file/d/1Skr58QPau27t5mFn_wJTFaFgyQW5iUPP/view?usp=sharing)
11. **韓燦洙**, 松本晋一, 川本淳平, 櫻井幸一, “AndroidマルウェアのAPI呼出し記録による分類及び個人情報漏えい検知,” *火の国情報シンポジウム, 3A-4*, 2016. [[Slides]](https://drive.google.com/file/d/1MFJlulvPfX_7fJc5s9IUMje8uLA5z0qJ/view?usp=sharing)
</div>
</details>


<hr>
### Non-refereed Oral Presentation/Talk
1. **C. Han**, “Challenges and Prospects for Cybersecurity in the AI Era” (AI時代におけるサイバーセキュリティの課題と展望), *ESTOC 2026 (Embedded Systems Technology Open Conference)*, Nagoya, Japan, Jun. 12, 2026. (Invited talk)
1. **C. Han**, “AI Security Evaluation Platform” (AIセキュリティ評価基盤), *5th Security Young Professionals Meetup (セキュリティ若手の会; LT & Networking)*, NICT, Tokyo, Japan, Jun. 13, 2026. (Venue-sponsor talk)
1. **C. Han**, “Early Detection and Tracing of Anomalous Scanning Campaigns Through Darknet Analysis,” *2025 Joint Workshop on Cybersecurity* (Northeastern University & University of Maryland), NICT, Tokyo, Japan, Aug. 6, 2025.
1. M. Umizaki, **C. Han**, and T. Ino, “Basics and Latest Updates of CURE” (CUREの基本と最新アップデート情報), *FY2025 Co-Nexus A (1st Session)*, Jul. 17, 2025.
1. **C. Han**, “Early Detection and Tracing of Anomalous Scanning Campaigns Through Darknet Analysis,” *KIIS–NICT International Joint Workshop: Unknown Threat and Trust in AI Security*, Tokyo, Japan, Dec. 20, 2024.
1. **C. Han**, “From Packets to Explanation: Enhancing NIDS with XAI and Cyber-Attack Analysis,” *FY2024 NICT Domestic Advisory Committee Site Visit*, NICT, Japan, Dec. 9, 2024. (Poster)
1. **C. Han**, “Darknet Analysis: Early Detection of Anomalous Scanning Activities,” *Research Gathering with National Taiwan University (NTU)*, Tokyo, Japan, Sep. 24, 2024.
1. **C. Han**, “Overview of Cybersecurity Laboratory in NICT and Recent Trends in AI Safety,” *2024 First Autonomous Driving Technology Development Innovation Project Demand Company Technology Committee Meeting*, KATECH, Korea, Aug, 2024.
1. **C. Han**, “Tracing Internet-wide Scanning Campaigns Based on Darknet Analysis,” *2023 TWN–NICT Cybersecurity Workshop*, Taipei, Taiwan, Dec. 5, 2023.
1. **C. Han**, “Darknet Network Traffic Analysis for Detecting IoT Attack Campaigns,” *Workshop on Cyber Defense and Resilience (NICT–BCCC)*, NICT, Tokyo, Japan, Dec. 1, 2023.
1. **C. Han**, “Progress Report on Darknet Analysis: Measurement Analysis and Tracing of Internet-Wide Scanner,” *CIC–NICT Workshop*, Canadian Institute for Cybersecurity (UNB), Canada, Aug. 4, 2023.
1. A. Tanaka, **C. Han**, and T. Takahashi, “Port Set Clustering for Internet-Wide Scanner,” *The 6th RIKEN-IMI-ISM-NUS-ZIB-MODAL-NHR Workshop on Advances in Classical and Quantum Algorithms for Optimization and Machine Learning*, Sep. 2022.
1. **C. Han**, “Real-time Detection of Malware Activities on Darknet by Estimating Anomalous Synchronization,” *French–Japanese Cybersecurity Intermediate Workshop 2021 (WG3)*, Feb. 25, 2021.
1. **C. Han**, “Real-time Detection of Anomalous Cooperation based on Darknet using Graphical Lasso,” *The 1st International Joint Conference on AI & Data Science*, Suwon, Korea, Nov. 2019.
1. **C. Han** et al., “A Fast Algorithm for Constructing Phylogenetic Trees with Application to IoT Malware Clustering,” *The 3rd Joint Workshop of TWISC and NICT*, Kinmen, Taiwan, Sep. 20–21, 2019.
1. **C. Han**, presentations at *KISTI–NICT / SCH Joint Security Workshops*, 2018–2024 (selected): “Real-time Detection of Malicious Cooperative Behaviors by the Graphical Lasso from Darknet Traffic” (NICT–SCH, Aug. 2018); “GLASSO Engine: Evaluation of Cyber Attack Detection Method based on Darknet Traffic Analysis” (KISTI–SCH–NICT, Dec. 2018); “A Fast Algorithm for Constructing Phylogenetic Trees with Application to IoT Malware Clustering” (7th NICT–KISTI–SCH, Oct. 2019); “Early Detection and Tracing of Anomalous Scanning Campaigns through Darknet Analysis” (9th KISTI–NICT, Nov. 2024).
1. **C. Han**, presentations at *NICTER Project Workshop*, 2018–2024 (selected): “Progress and Latest Detection Cases of glasso & NMF Engines” (11th, Nov. 2018); “Introduction to Research Activities on Darknet, Malware, and Livenet Analysis” (12th, Nov. 2019); “Real-time Detection of Malware Activities and Automatic Fingerprint Identification of Internet-wide Scanners” (14th, Nov. 2021, w/ R. Isawa and A. Tanaka); “Tracing Scanner Groups through Darknet Analysis” (16th, Nov. 2023, w/ A. Tanaka); “Between AI and Cybersecurity: Trials Toward Coexistence” (AIとサイバーセキュリティの狭間で：両立を目指した歩みと試行錯誤) (2024, Dec. 2024).

### Non-refereed Academic Magazine
1. T. Takahashi, K. Furumoto, and **C. Han**, “Cyber Wars: 2. Boosting Cybersecurity with Machine Learning Techniques,” *IPSJ Magazine, vol.61(7), pp.672-677*, Jul. 2020.

### Thesis
1. Real-time Detection of Malware Activities and Analysis of Behavioral Differences Between IoT Malware, Doctoral Dissertation, *ISEE, Kyushu University*, Date Accepted: 2021-01-12, Granted Date: 2021-03-24, Degree: Doctor of Engineering [[PDF]](https://catalog.lib.kyushu-u.ac.jp/opac_download_md/4475145/isee0693.pdf) [[Slides (in Japanese)]](https://drive.google.com/file/d/1jNFK8CPlbF7-diEdqFEt6e3nH_uJSviC/view?usp=sharing) [[Details]](http://hdl.handle.net/2324/4475145)
2. A study on real-time detection of malware activity by the graphical lasso and graph density, Master Thesis, *ISEE, Kyushu University*, Date Accepted: 2018-02-21, Granted Date: 2018-03-20, Degree: Master of Science [[Slides (in Japanese)]](https://drive.google.com/file/d/1caEugXNzXR_854WzpGKmtPkvUGk-bobr/view?usp=sharing)
3. Detection of Android malware by dynamic analysis using API call record, Bachelor Thesis，*EECS, Kyushu University*, Granted Date: 2016-03-25, Degree: Bachelor of Engineering [[Slides (in Japanese)]](https://drive.google.com/file/d/1TA8rwGobdpguwiWsboxEbWprviWPMe5M/view?usp=sharing)

<hr>
# Others

## Datasets

- **NICT Darknet Dataset 2022**: publicly released darknet traffic dataset ([website](https://csdataset.nict.go.jp/darknet-2022/)). Provided to 31 research groups/institutions (as of July 2026).

## Projects
- **Joint Research on AI Safety with US Specialized Organizations**, NICT, FY2025–FY2026, subsidy from the Ministry of Internal Affairs and Communications (MIC), Japan; FY2025: 250M JPY, FY2026: 300M JPY
- **Tenure-Track Researcher**, NICT, 2023–present, 4M JPY/year
- **NARLabs–NICT Joint Project**: Efficient and Effective Network Management and Cybersecurity, Apr. 2024–Mar. 2026, 5M JPY
- **NARLabs–NICT Joint Project**: NICTER (Network Incident analysis Center for Tactical Emergency Response), Apr. 2021–Mar. 2023, 5M JPY
- **MITIGATE**: Research and Development for Expansion of Radio Wave Resources (JPJ000254) — IoT malware behavior detection and remediation for efficient radio spectrum use; Yokohama National University (lead), MIC, Japan, 2020–2022, 1B JPY
- **PRISM (Public/Private R&D Investment Strategic Expansion Program), AI Technology Area**: R&D of a Hybrid High-Speed Cyber Attack Analysis Platform; NICT (lead), 2019, 200M JPY
- **NICTER Project** (Network Incident analysis Center for Tactical Emergency Response): [https://www.nicter.jp/en/](https://www.nicter.jp/en/)

## Awards/Honors
- CSEC Best Research Award, IPSJ (104th CSEC Workshop), 2024 (co-author)
- CSS Best Student Paper Award, IPSJ Computer Security Symposium 2021, 2021 (co-author)

## Teaching
- Part-time Lecturer, Tsuda University, FY2023–FY2024
  - Course: *Artificial Intelligence and Machine Learning* (人工知能・機械学習（演習付）, CS3032), Department of Computer Science

## Mentoring

### Graduate Students (Kyushu University; including students supervised as Visiting Assistant Professor)

**Ph.D.**

- Vincent Takahashi, Kyushu University, 2025–present
- Kohei Miyamoto, Kyushu University, 2021–2024
- Tianxiang He, Kyushu University, 2018–2023

**Master’s**

- Keiji Inoue, Kyushu University, 2025–present
- Kosuke Nikawa, Kyushu University, 2023–2025
- Shota Kawanaka, Kyushu University, 2022–2024 (RA at NICT, 2024)
- Kensei Ma, Kyushu University, 2022–2024
- Satoshi Takada, Kyushu University, 2021–2023
- Masazumi Iida, Kyushu University, 2022–2023
- Kei Oshio, Kyushu University, 2022–2023
- Yoshikatsu Kashiwabara, Kyushu University, 2022–2023
- Ryosuke Ishibashi, Kyushu University, 2020–2022
- Hiroki Goto, Kyushu University, 2020–2022
- Reo Kawasoe, Kyushu University, 2019–2021
- Wanju Wei, Kyushu University, 2019–2020
- Hirohito Nakahara, Kyushu University, 2016–2017

### Research Assistants (RA), NICT
- Soma Kato, Kyushu University, 2025–present
- Shu Akabane, Kanagawa Institute of Technology, 2024
- Yuta Nakagawa, Yokohama National University, 2019

### Interns and Cooperative Visiting Researchers
- Mainak Basak, Hankyong National University (HNU), Korea, 2026
- Hyeonjin Jung, Yonsei University, Korea, 2026
- Han-Ju Lee, Yonsei University, Korea, 2025–2026
- Jin-Seong Kim, Yonsei University, Korea, 2025–2026
- Shincheol Lee, Dongguk University, Korea, 2025
- Insik Choi, Sejong University, Korea, 2025
- Thomas Winninger, Télécom SudParis, France, 2025
- Yu-Hsun Lee, National Institute of Cyber Security (NICS), Taiwan, 2024
- Meng-Hsueh Yu, National Institute of Cyber Security (NICS), Taiwan, 2024
- Martin Horth, Télécom SudParis, France, 2023
- Vincent Lin, National Taiwan University (NTU), Taiwan, 2023
- Tien-Ning Lee, National Yang Ming Chiao Tung University (NYCU), Taiwan, 2023

## Patents
- Fingerprint Identification System and Method, Japanese Patent Applications 2022-123952 and 2022-123955, 2022

## Media & Exhibitions
- Corporate exhibition, Annual Conference of the Japanese Society for Artificial Intelligence (JSAI), 2026: CREATE — AI Security Evaluation Platform
- INTEROP Tokyo exhibition & demo, 2026: CREATE — AI Security Evaluation Platform
- CEATEC exhibition & demo, 2025: LLM Security Evaluation and Attack/Defense Frontiers
- NICT Open House exhibition & demo, 2025–2026: AI security evaluation and defense
- **C. Han**, “Discovering Cyber Threats with AI,” *Nikkan Kogyo Shimbun* (NICT Advanced Research, No. 141), Jul. 28, 2020 [[PDF]](https://www.nict.go.jp/gaibu-keisai/oi25v200000005r2-att/141.pdf)

## Memberships
- Information Processing Society of Japan (IPSJ)

<hr>
## Professional Services

### Editorial Service
- Editorial Committee, *Journal of Information Processing* (IPSJ), Special Issue on Computer Security Technologies for AI Society, 2024–2025
- Editorial Committee, *Journal of Information Processing* (IPSJ), Special Issue on Cybersecurity Technologies for Secure Supply-Chain, 2023–2024

### Conference/Workshop Organization
- Special Session Organizer (SS-19: AI Security), *SCIS&ISIS 2026*, Hachioji, Tokyo, Japan, Nov. 2–5, 2026 [[website]](https://soft-cr.org/scis/2026/special_session.html)
- Organizing Committee, *NICT AI Security Workshop: Strengthening U.S.–Japan Collaboration on AI Security*, Cosmos Club, Washington, DC, USA, Jan. 22, 2026 (sponsored by CREATE, NICT)
- Organizing Committee, *Asia Symposium on AI and Cybersecurity* (KIIS–NICT; supported by KOFST), NICT, Japan, Sep. 25–26, 2025
- Organizing Committee, *KIIS–NICT International Joint Workshop: Unknown Threat and Trust in AI Security* (KIIS; supported by KOFST), Tokyo, Japan, Dec. 20–21, 2024
- Organizing Committee, *The 9th KISTI–NICT International Joint Workshop*, Tokyo, Japan, Nov. 11–12, 2024
- Local Arrangement Chair, International Conference on Artificial Intelligence Computing and Systems (AICompS), 2025

### Program Committee Member
- IEEE Conference on Dependable and Secure Computing (DSC), 2026; 2024 (Poster Session Chair)
- International Conference on Neural Information Processing (ICONIP), 2024, 2021, 2019
- IEEE International Joint Conference on Neural Networks (IJCNN), 2024

### Session Chair
- *The 9th KISTI–NICT International Joint Workshop*, Tokyo, Japan, Nov. 11, 2024
- International Conference on Information Systems Security and Privacy (ICISSP), 2023
- Computer Security Symposium (CSS), 2021, 2020

### Review Experiences
- IEEE Transactions on Reliability, 2025, 2024
- IPSJ Journal of Information Processing, 2025, 2024, 2022, 2021
- International Conference on Artificial Intelligence Computing and Systems (AICompS), 2025
- IEEE Conference on Dependable and Secure Computing (DSC), 2024
- International Conference on Neural Information Processing (ICONIP), 2024, 2021, 2019
- IEEE International Joint Conference on Neural Networks (IJCNN), 2024
- Peer-to-Peer Networking and Applications, 2023
- The Journal of Supercomputing, 2023
- Computer Security Symposium (CSS), 2021, 2020, 2019
- Finnish-Russian University Cooperation in Telecommunication (FRUCT), 2021, 2020
- IEEE International Conference on Smart Computing (SMARTCOMP), 2021
- IEICE Transactions on Information and Systems, 2021
- International Computer Symposium (ICS), 2020
- IEICE Transactions on Communications, 2019
- International Journal of Information Security, 2019
- Annual Computer Security Applications Conference (ACSAC), 2018
